name: Liara CD (Monolithic)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: Move Frontend Build
        run: |
          mv frontend/dist backend/dist

      - name: Install Liara CLI
        run: npm i -g @liara/cli

      - name: Deploy to Liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          cd backend
          liara deploy --app="antibioticplay" --api-token="$LIARA_TOKEN" --detach